; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Mon May 03 2021 02:00:54 GMT+0200 (Mitteleuropäische Sommerzeit)

