; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.6 on Tue Jan 14 2020 09:54:38 GMT+0100 (Mitteleuropäische Normalzeit)
; Wait for set temperatures to be reached
M116 P0

