; generated by PrusaSlicer 2.3.1+x64 on 2021-06-26 at 13:34:50 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

M107
;TYPE:Custom
M291 P"Printing Model: Tool_0, Material: PLA" R"Print Info Box" S3
G28											; Home all Axes
M190 S25			; Set Bed Probing Temp and wait for it
M291 P"Wait for Bed Probing Temp" R"Print Info Box" S1 T3
G29											; Run mesh grid compensation
T0 												; Select Tool 0
G1 X373 Y40 F50000 							; Move to Position over Purge bucket for dropping filament
M109 S25 T0 			; Now Set Extruder Temp and wait
M83 											; Set extruder to relative mode
M116 											; Wait for temperatures
G92 E0.0 										; reset extruder
M98 P"brush.g" 								; start brush.g (WasteBox)
;M98 P"prime.g" 								; start prime.g (Introline)
M291 P"Printing started !" R"Printing.." S1 T3 	; Zeige Nachricht
M83 											; relative extrusion mode
; Ende Start G-Code
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
T0
G92 E0
; Filament gcode
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z0.200 F10800.000
G1 E-2.00000 F2400.000
G92 E0
G1 Z0.300 F10800.000
G1 X152.448 Y153.964
G1 Z0.200
G1 E2.00000 F2400.000
M204 S1000
;TYPE:Skirt
;WIDTH:0.42
G1 F1200.000
G1 X152.988 Y153.119 E2.03050
G1 X153.401 Y152.758 E2.04719
G1 X153.877 Y152.485 E2.06387
G1 X154.397 Y152.313 E2.08055
G1 X154.942 Y152.246 E2.09723
G1 X195.004 Y152.246 E3.31567
G1 X196.028 Y152.445 E3.34740
G1 X196.905 Y153.011 E3.37913
G1 X197.508 Y153.862 E3.41086
G1 X197.751 Y154.876 E3.44259
G1 X197.754 Y195.049 E4.66439
G1 X197.552 Y196.036 E4.69502
G1 X197.012 Y196.881 E4.72552
G1 X196.589 Y197.249 E4.74258
G1 X196.101 Y197.525 E4.75963
G1 X195.567 Y197.695 E4.77668
G1 X195.009 Y197.754 E4.79374
G1 X154.951 Y197.754 E6.01205
G1 X153.964 Y197.552 E6.04268
G1 X153.119 Y197.012 E6.07318
G1 X152.751 Y196.589 E6.09024
G1 X152.475 Y196.101 E6.10729
G1 X152.305 Y195.567 E6.12434
G1 X152.246 Y195.009 E6.14140
G1 X152.246 Y154.951 E7.35971
G1 X152.436 Y154.023 E7.38851
G1 E5.38851 F2400.000
G92 E0
G1 Z0.300 F10800.000
G1 X194.730 Y155.567
G1 Z0.200
G1 E2.00000 F2400.000
;TYPE:External perimeter
G1 F1200.000
G1 X194.790 Y155.507 E2.00258
G1 X194.790 Y194.493 E3.18829
G1 X194.730 Y194.433 E3.19087
G1 X194.730 Y155.627 E4.37110
G1 X194.815 Y155.567 F10800.000
G1 E-5.62890 F2400.000
G92 E0
G1 Z0.300 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T1
G92 E0
; Filament gcode
G1 E-2.00000 F2400.000
G92 E0
G1 X197.169 Y154.027 F10800.000
G1 Z0.200
G1 E2.00000 F2400.000
;TYPE:Skirt
G1 F1200.000
G1 X197.375 Y154.908 E2.02752
G1 X197.377 Y195.038 E3.24804
G1 X197.202 Y195.895 E3.27464
G1 X196.729 Y196.631 E3.30125
G1 X195.945 Y197.181 E3.33036
G1 X195.005 Y197.377 E3.35958
G1 X154.962 Y197.377 E4.57744
G1 X154.105 Y197.202 E4.60404
G1 X153.369 Y196.729 E4.63065
G1 X152.819 Y195.945 E4.65976
G1 X152.623 Y195.005 E4.68898
G1 X152.623 Y154.962 E5.90684
G1 X152.798 Y154.105 E5.93344
G1 X153.271 Y153.369 E5.96005
G1 X154.041 Y152.825 E5.98871
G1 X154.957 Y152.623 E6.01725
G1 X195.004 Y152.623 E7.23522
G1 X195.892 Y152.797 E7.26274
G1 X196.648 Y153.287 E7.29014
G1 X197.134 Y153.978 E7.31583
G1 E5.31583 F2400.000
G92 E0
G1 Z0.300 F10800.000
G1 X194.433 Y194.730
G1 Z0.200
G1 E2.00000 F2400.000
;TYPE:External perimeter
G1 F1200.000
G1 X194.493 Y194.790 E2.00258
G1 X155.507 Y194.790 E3.18829
G1 X155.567 Y194.730 E3.19087
G1 X194.373 Y194.730 E4.37110
G1 X194.433 Y194.815 F10800.000
G1 E-5.62890 F2400.000
G92 E0
G1 Z0.300 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T2
G92 E0
; Filament gcode
G1 E-2.00000 F2400.000
G92 E0
G1 X155.270 Y194.433 F10800.000
G1 Z0.200
G1 E2.00000 F2400.000
G1 F1200.000
G1 X155.210 Y194.493 E2.00258
G1 X155.210 Y155.507 E3.18829
G1 X155.270 Y155.567 E3.19087
G1 X155.270 Y194.373 E4.37110
G1 X155.185 Y194.433 F10800.000
G1 E-5.62890 F2400.000
G92 E0
G1 Z0.300 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T3
G92 E0
; Filament gcode
G1 E-2.00000 F2400.000
G92 E0
G1 X155.567 Y155.270 F10800.000
G1 Z0.200
G1 E2.00000 F2400.000
G1 F1200.000
G1 X155.507 Y155.210 E2.00258
G1 X194.493 Y155.210 E3.18829
G1 X194.433 Y155.270 E3.19087
G1 X155.627 Y155.270 E4.37110
G1 X155.567 Y155.185 F10800.000
M106 S237.15
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 Z0.400 F10800.000
G1 X155.627 Y155.255
M204 S800
;WIDTH:0.45
G1 F1500.000
G1 X155.573 Y155.255 E4.37287
G1 X155.543 Y155.225 E4.37426
G1 X194.457 Y155.225 E5.65193
G1 X194.427 Y155.255 E5.65332
G1 X155.687 Y155.255 E6.92528
M204 S1000
G1 X155.600 Y155.208 F10800.000
G1 E-3.07472 F2400.000
G92 E0
; Filament-specific end gcode 
;END gcode for filament
T0
G92 E0
; Filament gcode
G1 Z0.500 F10800.000
G1 X194.745 Y155.573
G1 Z0.400
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.775 Y155.543 E10.00139
G1 X194.775 Y194.457 E11.27906
G1 X194.745 Y194.427 E11.28045
G1 X194.745 Y155.633 E12.55417
M204 S1000
G1 X194.787 Y155.573 F10800.000
G1 E2.55417 F2400.000
G92 E0
G1 Z0.500 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T1
G92 E0
; Filament gcode
G1 X194.427 Y194.745
G1 Z0.400
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.457 Y194.775 E10.00139
G1 X155.543 Y194.775 E11.27906
G1 X155.573 Y194.745 E11.28045
G1 X194.367 Y194.745 E12.55417
M204 S1000
G1 X194.427 Y194.787 F10800.000
G1 E2.55417 F2400.000
G92 E0
G1 Z0.500 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T2
G92 E0
; Filament gcode
G1 X155.255 Y194.427
G1 Z0.400
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X155.225 Y194.457 E10.00139
G1 X155.225 Y155.543 E11.27906
G1 X155.255 Y155.573 E11.28045
G1 X155.255 Y194.367 E12.55417
M204 S1000
G1 X155.213 Y194.427 F10800.000
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
G1 Z0.600 F10800.000
M204 S800
G1 F1500.000
G1 X155.255 Y194.427 E12.55614
G1 X155.225 Y194.457 E12.55754
G1 X155.225 Y155.543 E13.83520
G1 X155.255 Y155.573 E13.83659
G1 X155.255 Y194.307 E15.10835
M204 S1000
G1 X155.203 Y194.397 F10800.000
G1 E5.10835 F2400.000
G92 E0
G1 Z0.700 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T0
G92 E0
; Filament gcode
G1 X194.745 Y194.307
G1 Z0.600
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.745 Y155.573 E11.27175
G1 X194.775 Y155.543 E11.27315
G1 X194.775 Y194.457 E12.55081
G1 X194.745 Y194.427 E12.55220
G1 X194.745 Y194.367 E12.55417
M204 S1000
G1 X195.078 Y194.084 F10800.000
G1 E2.55417 F2400.000
G92 E0
G1 Z0.700 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T1
G92 E0
; Filament gcode
G1 X194.427 Y194.745
G1 Z0.600
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.457 Y194.775 E10.00139
G1 X155.543 Y194.775 E11.27906
G1 X155.573 Y194.745 E11.28045
G1 X194.367 Y194.745 E12.55417
M204 S1000
G1 X194.427 Y194.787 F10800.000
G1 E2.55417 F2400.000
G92 E0
G1 Z0.700 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T3
G92 E0
; Filament gcode
G1 X194.367 Y155.255
G1 Z0.600
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X155.573 Y155.255 E11.27372
G1 X155.543 Y155.225 E11.27512
G1 X194.457 Y155.225 E12.55278
G1 X194.427 Y155.255 E12.55417
M204 S1000
G1 X193.967 Y155.255 F10800.000
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
G1 Z0.800 F10800.000
M204 S800
G1 F1500.000
G1 X155.573 Y155.255 E13.82987
G1 X155.543 Y155.225 E13.83126
G1 X194.439 Y155.225 E15.10835
M204 S1000
G1 X194.627 Y154.909 F10800.000
G1 E5.10835 F2400.000
G92 E0
; Filament-specific end gcode 
;END gcode for filament
T0
G92 E0
; Filament gcode
G1 X194.766 Y155.552 F10800.000
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.775 Y194.457 E11.27738
G1 X194.745 Y194.427 E11.27877
G1 X194.745 Y155.603 E12.55348
M204 S1000
G1 X194.420 Y155.352 F10800.000
G1 E2.55348 F2400.000
G92 E0
G1 Z0.900 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T1
G92 E0
; Filament gcode
G1 X194.427 Y194.745
G1 Z0.800
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.457 Y194.775 E10.00139
G1 X155.543 Y194.775 E11.27906
G1 X155.573 Y194.745 E11.28045
G1 X194.367 Y194.745 E12.55417
M204 S1000
G1 X194.427 Y194.787 F10800.000
G1 E2.55417 F2400.000
G92 E0
G1 Z0.900 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T2
G92 E0
; Filament gcode
G1 X155.255 Y194.427
G1 Z0.800
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X155.225 Y194.457 E10.00139
G1 X155.225 Y155.543 E11.27906
G1 X155.255 Y155.573 E11.28045
G1 X155.255 Y194.367 E12.55417
M204 S1000
G1 X155.213 Y194.427 F10800.000
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
G1 Z1.000 F10800.000
M204 S800
G1 F1500.000
G1 X155.255 Y194.427 E12.55614
G1 X155.225 Y194.457 E12.55754
G1 X155.225 Y155.543 E13.83520
G1 X155.255 Y155.573 E13.83659
G1 X155.255 Y194.307 E15.10835
M204 S1000
G1 X155.203 Y194.397 F10800.000
G1 E5.10835 F2400.000
G92 E0
G1 Z1.100 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T0
G92 E0
; Filament gcode
G1 X194.745 Y194.307
G1 Z1.000
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.745 Y155.573 E11.27175
G1 X194.775 Y155.543 E11.27315
G1 X194.775 Y194.457 E12.55081
G1 X194.745 Y194.427 E12.55220
G1 X194.745 Y194.367 E12.55417
M204 S1000
G1 X195.078 Y194.084 F10800.000
G1 E2.55417 F2400.000
G92 E0
G1 Z1.100 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T1
G92 E0
; Filament gcode
G1 X194.427 Y194.745
G1 Z1.000
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X194.457 Y194.775 E10.00139
G1 X155.543 Y194.775 E11.27906
G1 X155.573 Y194.745 E11.28045
G1 X194.367 Y194.745 E12.55417
M204 S1000
G1 X194.427 Y194.787 F10800.000
G1 E2.55417 F2400.000
G92 E0
G1 Z1.100 F10800.000
; Filament-specific end gcode 
;END gcode for filament
T3
G92 E0
; Filament gcode
G1 X194.367 Y155.255
G1 Z1.000
G1 E10.00000 F2400.000
M204 S800
G1 F1500.000
G1 X155.573 Y155.255 E11.27372
G1 X155.543 Y155.225 E11.27512
G1 X194.457 Y155.225 E12.55278
G1 X194.427 Y155.255 E12.55417
M204 S1000
G1 X193.967 Y155.255 F10800.000
G1 E10.55417 F2400.000
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
; Filament-specific end gcode 
;END gcode for filament
; Filament-specific end gcode 
;END gcode for filament
; Filament-specific end gcode 
;END gcode for filament
G1 E-2 F2000 ; retract filament
T-1
G1 Z10.000
M106 S0 ; turn off part cooling fan
G1 X0 Y300 F3000 ; move to cooling position / Hinten Links
M140 S0 ; turn off bed
M104 S0 ; turn off extruder
G90 ; absolute positioning
M84 ; disable motors
M300 S250 P1000 ; Play notification beep
M291 P"You may now remove your part. CAUTION! Print Surface may still be HOT!" R"Print Finished." S1 T0
M83 ;relative extrusion mode
M81 S1 ; shutdown after all thermostatic fans have turned off
M291 P"Printing finished !" R"Printing.." S1 T0	; Zeige Nachricht
; filament used [mm] = 17.98, 17.90, 12.59, 12.59
; filament used [cm3] = 0.04, 0.04, 0.03, 0.03
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 46s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = /Volumes/MultiMedia/3D-Druck/CrazyCreatorCube/Software/Slicer/Bed.stl
; bed_custom_texture = /Volumes/MultiMedia/3D-Druck/CrazyCreatorCube/Software/Slicer/CCC-Logo_Neu01.png
; bed_shape = 0x0,350x0,350x350,0x350
; bed_temperature = 25,25,25,25
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 8
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100,100,100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1,1,1,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0,0,0
; disable_fan_first_layers = 1,1,1,1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = T-1\nG1 E-2 F2000 ; retract filament\nM106 S0 ; turn off part cooling fan\nG1 X0 Y300 F3000 ; move to cooling position / Hinten Links\nM140 S0 ; turn off bed\nM104 S0 ; turn off extruder\nG90 ; absolute positioning\nM84 ; disable motors\nM300 S250 P1000 ; Play notification beep\nM291 P"You may now remove your part. CAUTION! Print Surface may still be HOT!" R"Print Finished." S1 T0\nM83 ;relative extrusion mode\nM81 S1 ; shutdown after all thermostatic fans have turned off\nM291 P"Printing finished !" R"Printing.." S1 T0	; Zeige Nachricht\n
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #0000FF;#80FF08;#FFFF66;#800040
; extruder_offset = 0x0,0x0,0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.97,0.97,0.97,0.97
; extrusion_width = 0.45
; fan_always_on = 0,0,0,0
; fan_below_layer_time = 60,60,60,60
; filament_colour = #666666;#666666;#666666;#666666
; filament_cooling_final_speed = 3.4,3.4,3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2,2.2,2.2
; filament_cooling_moves = 4,4,4,4
; filament_cost = 20,20,20,20
; filament_density = 0,0,0,0
; filament_diameter = 1.75,1.75,1.75,1.75
; filament_load_time = 0,0,0,0
; filament_loading_speed = 28,28,28,28
; filament_loading_speed_start = 3,3,3,3
; filament_max_volumetric_speed = 0,0,0,0
; filament_minimal_purge_on_wipe_tower = 15,15,15,15
; filament_notes = ;;;
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = TESTFILAMENT-PLA-NX2-Extrudr;TESTFILAMENT-PLA-NX2-Extrudr;TESTFILAMENT-PLA-NX2-Extrudr;TESTFILAMENT-PLA-NX2-Extrudr
; filament_soluble = 0,0,0,0
; filament_spool_weight = 0,0,0,0
; filament_toolchange_delay = 0,0,0,0
; filament_type = PLA;PLA;PLA;PLA
; filament_unload_time = 0,0,0,0
; filament_unloading_speed = 90,90,90,90
; filament_unloading_speed_start = 100,100,100,100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 10%
; fill_pattern = cubic
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 25,25,25,25
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 25,25,25,25
; full_fan_speed_layer = 0,0,0,0
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100,100,100
; max_layer_height = 0,0,0,0.1
; max_print_height = 310
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 60,60,60,60
; min_layer_height = 0.05,0.05,0.05,0.05
; min_print_speed = 10,10,10,10
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4,0.4,0.4,0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 40
; perimeters = 6
; physical_printer_settings_id = CCC
; post_process = 
; print_settings_id = 0.20mm QUALITY - BLV
; printer_model = 
; printer_notes = 
; printer_settings_id = CrazyCreatorCube
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2,2,2
; retract_before_wipe = 0%,0%,0%,0%
; retract_layer_change = 0,0,0,0
; retract_length = 2,2,2,2
; retract_length_toolchange = 10,10,10,10
; retract_lift = 0.1,0.1,0.1,0
; retract_lift_above = 0,0,0,0
; retract_lift_below = 0,0,0,0
; retract_restart_extra = 0,0,0,0
; retract_restart_extra_toolchange = 0,0,0,0
; retract_speed = 40,40,40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirts = 2
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5,5,5,5
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n"
; start_gcode = M291 P"Printing Model: [input_filename_base], Material: [filament_type]" R"Print Info Box" S3\nG28											; Home all Axes\nM190 S[first_layer_bed_temperature]			; Set Bed Probing Temp and wait for it\nM291 P"Wait for Bed Probing Temp" R"Print Info Box" S1 T3\nG29											; Run mesh grid compensation\nT0 												; Select Tool 0\nG1 X373 Y40 F50000 							; Move to Position over Purge bucket for dropping filament\nM109 S[first_layer_temperature] T0 			; Now Set Extruder Temp and wait\nM83 											; Set extruder to relative mode\nM116 											; Wait for temperatures\nG92 E0.0 										; reset extruder\nM98 P"brush.g" 								; start brush.g (WasteBox)\n;M98 P"prime.g" 								; start prime.g (Introline)\nM291 P"Printing started !" R"Printing.." S1 T3 	; Zeige Nachricht\nM83 											; relative extrusion mode\n; Ende Start G-Code
; support_material = 1
; support_material_angle = 0
; support_material_auto = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 25,25,25,25
; template_custom_gcode = 
; thin_walls = 0
; threads = 12
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 8
; top_solid_min_thickness = 0.6
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0,0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 202.821
; wipe_tower_y = 95.1102
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70
; wiping_volumes_matrix = 0,140,140,140,140,0,140,140,140,140,0,140,140,140,140,0
; xy_size_compensation = 0
; z_offset = 0
